version: "3.9"
services:
  node1:
    image: "demo_image"
    environment:
      - NODENUM=1
    ports:
      - "8001:8001"
    networks:
      computation_network:
        ipv4_address: 10.5.0.2

  node2:
    image: "demo_image"
    environment:
      - NODENUM=2
    ports:
      - "8001:8001"
    networks:
      computation_network:
        ipv4_address: 10.5.0.3

  node3:
    image: "demo_image"
    environment:
      - NODENUM=3
    ports:
      - "8001:8001"
    networks:
      computation_network:
          ipv4_address: 10.5.0.4

networks:
  computation_network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.5.0.0/16

